### ISSUE TITLE
Can't make first tab selected by default

### ISSUE THREAD

**Issue by vitalii-tym** [yervandsar/SmoothTab#3]
SmoothTabView has `tapItem(at:)` to programmatically make some tab selected.
However, attempt to select the very first one (at index 0) gives no results. Most probably because of the `if oldValue != selectedSegmentIndex` check in `selectedSegmentIndex`'s `didSet`

As a workaround have to do this:

> smoothTabView.tapItem(at: 1)
> smoothTabView.tapItem(at: 0)

**Comment by yervandsar** [comment]
Hi @vitalii-tym, thanks a lot, this issue will be fixed in next version.
